// nginx and certs
setting up nginx https://gist.github.com/bradtraversy/cd90d1ed3c462fe3bddd11bf8953a896
setting up ssl certs - https://certbot.eff.org/lets-encrypt/ubuntufocal-nginx

// Droplet
digital ocean droplet - select docker Its build on top of Ubuntu 20.14

//Domain Names
purchase domain names through name cheap and set custom DNS to ns1.digitalocean.com, ns2.digitalocean.com, ns3.digitalocean.com
In DigitalOcean select "Networking" then enter domain
* enter @ symbol then the desired droplet
* enter www then the desired droplet


// Error logging.
// We should use a service like https://sentry.io/welcome/
