version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    container_name: mound_city_postgress_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mound_city
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  admin:
    image: dpage/pgadmin4
    container_name: mound_city_db_admin
    ports:
      - "5050:80"
    depends_on:
      - db
      - reverse-proxy
    environment:
      - PGADMIN_DEFAULT_EMAIL=atwilliams88@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password

  web:
    image: express-starter
    container_name: mound_city_express_app
    volumes:
      - ./logs/combined.log:/logs/combined.log
      - ./logs/error.log:/logs/error.log
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - PORT=3000
      - PGUSER=postgres
      - PGPORT=5432;
      - PGDATABASE=mound_city
      - PGPASSWORD=password
      - PGHOST=db
    depends_on:
      - db
    ports:
      - "3000:3000"

  reverse-proxy:
    image: nginx
    container_name: mound_city_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - web
    volumes:
      # - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - ./reverse_proxy/nginx.conf:/etc/nginx/conf.d

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - web
      - reverse-proxy
    command: certonly --webroot --webroot-path=/var/www/html --email atwilliams88dev@gmail.com --agree-tos --no-eff-email --staging -d moundcity.io  -d www.moundcity.io
