version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    restart: on-failure
    container_name: ${DB_CONTAINER_NAME}
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  admin:
    image: dpage/pgadmin4
    container_name: ${PG_ADMIN_CONTAINER_NAME}
    restart: on-failure
    ports:
      - "5454:5454/tcp"
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGPASSWORD}
      - PGADMIN_LISTEN_PORT=5454

  web:
    image: express-starter
    container_name: ${EXPRESS_CONTAINER_NAME}
    volumes:
      - ./logs/combined.log:/logs/combined.log
      - ./logs/error.log:/logs/error.log
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - PORT=${EXPRESS_PORT}
      - PGUSER=${PGUSER}
      - PGPORT=${PGPORT};
      - PGDATABASE=${PGDATABASE}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=db
      - PHONE_NUMBER=${PHONE_NUMBER}
      - EMAIL=${EMAIL}
      - ZOOM=${ZOOM}
    depends_on:
      - db
      - admin
    ports:
      - "3000:3000"
